---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: karpenter
    namespace: flux-system
  interval: 1h0s
  releaseName: karpenter
  targetNamespace: kube-system
  values:
    settings:
      clusterName: infra
      interruptionQueue: infra
    controller:
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 1Gi
