---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: karpenter
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://public.ecr.aws/karpenter/karpenter
  ref:
    tag: 1.0.5
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: karpenter
    namespace: flux-system
  interval: 1h0s
  releaseName: karpenter
  targetNamespace: kube-system
  values:
    settings:
      clusterName: workshop
      interruptionQueue: workshop
    controller:
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 1Gi
