kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
  name: workshop
  version: "1.30"
  region: us-west-2
  tags:
    ucsb:environment: development
    ucsb:environment:name: devops
    ucsb:dept:INFR:retain-until: 2024-10-19
    karpenter.sh/discovery: infra
availabilityZones:
  - us-west-2a
  - us-west-2b
  - us-west-2c
iamIdentityMappings:
  - arn: arn:aws:iam::619984000261:role/ucsb-idp-administrator
    groups:
      - system:masters
    noDuplicateARNs: true # prevents shadowing of ARNs
  - arn: "arn:aws:iam::619984000261:role/KarpenterNodeRole-workshop"
    username: system:node:{{EC2PrivateDNSName}}
    groups:
      - system:bootstrappers
      - system:nodes
      ## If you intend to run Windows workloads, the kube-proxy group should be specified.
      # For more information, see https://github.com/aws/karpenter/issues/5099.
      # - eks:kube-proxy-windows
iam:
  withOIDC: true
  podIdentityAssociations:
  - namespace: kube-system
    serviceAccountName: karpenter
    roleName: workshop-karpenter
    permissionPolicyARNs:
      - arn:aws:iam::619984000261:policy/KarpenterControllerPolicy-workshop
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: aws-system
      wellKnownPolicies:
        awsLoadBalancerController: true
      roleName: eks-workshop-lb-controller-role
    - metadata:
        name: aws-cloudwatch-agent
        namespace: aws-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      roleName: eks-workshop-cloudwatch-metrics
    - metadata:
        name: aws-fluent-bit
        namespace: aws-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      roleName: eks-workshop-fluent-bit
addons:
  - name: vpc-cni
    version: latest
  - name: kube-proxy
    version: latest
  - name: coredns
    version: latest
  - name: eks-pod-identity-agent
    version: latest
managedNodeGroups:
  - name: workshop-graviton-workers
    instanceType: m7g.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 5
    privateNetworking: true
addonsConfig:
  autoApplyPodIdentityAssociations: true
